#Just run#
#docker-compose up#
version: '3.4'

services:
#MONGO CONTAINER#
#inside container run: "mongo"#
  databasemongo:
   build:
    context: .
    target: databasemongo
   image: backend_node:databasemongo
   ports:
    - 27017:27017
   command: ['mongod', "--bind_ip_all"]
   networks:
     - redeapi
   stdin_open: true
   tty: true

networks:
    redeapi:
volumes:
    dbdata: